### ISSUE TITLE
Location of images in storymap9 is still dav0

### ISSUE THREAD

**Issue by rebert** [geoadmin/mf-swissguesser#84]
Salut Marc

The location of storymap9 is still dav0. 
[Link to storymap9 without coresponding images ](http://storymaps.geo.admin.ch/storymaps/storymap9/?lang=de)

**Alternative 1: Fix the storymap**
Paulo and I copied the images linked to bgdi scratch:
\\v0t0020a.adr.admin.ch\kogis\igeb\BGDI\bgdiscratch\kgs

- As the deploy script is pointing to servers not existing any more, I did not dear to touch the thing.
- Neither I am sure if we want to add the 7'000 images to the github project.

**Alternative 2: Remove the storymap**
- Removing the storymap - Who decides? @davidoesch still active p.ex. [here](http://www.babs.admin.ch/de/aufgabenbabs/kgs/inventar.html)

Tobias

**Comment by davidoesch** [comment]
Storymap 9 will be decomissioned by daniela in Q4 2017---and therefore stop here the work.

**Comment by procrastinatio** [comment]
I though it was long dead already

**Comment by procrastinatio** [comment]
No more storymaps
